
services:

  # ----------------------------
  # 3. Django Backend API
  # ----------------------------
  - type: web
    name: oelp-backend
    env: python
    buildCommand: pip install -r requirements.txt && python oelp_backend/manage.py collectstatic --noinput
    startCommand: bash -c "python oelp_backend/manage.py migrate --noinput && gunicorn --chdir oelp_backend oelp_backend.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: oelp-backend.onrender.com
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
    # preDeployCommand is not supported on free tier; handled via build/start commands

  # ----------------------------
  # 4. Frontend React App
  # ----------------------------
  - type: web
    name: oelp-frontend
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://oelp-backend.onrender.com/api
    routes:
      # Single Page App routing: route all paths to index.html
      - type: rewrite
        source: /dashboard
        destination: /index.html
      - type: rewrite
        source: /crops
        destination: /index.html
      - type: rewrite
        source: /fields
        destination: /index.html
      - type: rewrite
        source: /subscriptions
        destination: /index.html
      - type: rewrite
        source: /practices
        destination: /index.html
      - type: rewrite
        source: /reports
        destination: /index.html
      - type: rewrite
        source: /settings
        destination: /index.html
      - type: rewrite
        source: /
        destination: /index.html
