
services:

  # ----------------------------
  # 3. Django Backend API
  # ----------------------------
  - type: web
    name: oelp-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn oelp_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: oelp-backend.onrender.com
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
    # Run DB migrations & collect static before each deploy
    preDeployCommand: |
      python oelp_backend/manage.py migrate --noinput
      python oelp_backend/manage.py collectstatic --noinput

  # ----------------------------
  # 4. Frontend React App
  # ----------------------------
  - type: web
    name: oelp-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
