# Generated by Django 4.2.15 on 2025-11-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_add_refund_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', help_text='Primary role of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='models_app.role'),
        ),
    ]
