# Generated by Django 4.2.15 on 2025-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('alert', 'Alert'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_read'], name='models_app__receive_fa9ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='models_app__created_02bb31_idx'),
        ),
    ]
