# Generated by Django 4.2.15
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('models_app', '0007_alter_notification_options_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
