# Generated by Django 4.2.15 on 2025-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_alter_notification_options_remove_customuser_role_and_more'),  # Changed from 0008 to 0007
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cause',
            field=models.CharField(choices=[('system', 'System Notification'), ('user_action', 'User Action'), ('alert', 'Alert'), ('update', 'Update'), ('reminder', 'Reminder'), ('support', 'Support Request')], default='user_action', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='direction',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='received', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', 'direction'], name='models_app__sender__700a72_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['region'], name='models_app__region_ba8f05_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['crop_type'], name='models_app__crop_ty_368421_idx'),
        ),
    ]
