# Generated by Django 4.2.15 on 2025-11-25 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_notification_cause_notification_crop_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(
                    choices=[
                        ('crop', 'Crop Management'),
                        ('transaction', 'Payment/Transaction'),
                        ('analysis', 'Data Analysis'),
                        ('software_issue', 'Software Issue'),
                        ('technical', 'Technical Support'),
                        ('general', 'General Inquiry')
                    ],
                    default='general',
                    max_length=32
                )),
                ('forwarded_to_role', models.CharField(
                    blank=True,
                    help_text='Role to which ticket is forwarded (admin, agronomist, analyst, developer, business)',
                    max_length=50,
                    null=True
                )),
                ('status', models.CharField(
                    choices=[
                        ('open', 'Open'),
                        ('assigned', 'Assigned'),
                        ('in_progress', 'In Progress'),
                        ('resolved', 'Resolved'),
                        ('closed', 'Closed')
                    ],
                    default='open',
                    max_length=20
                )),
                ('priority', models.CharField(
                    choices=[
                        ('low', 'Low'),
                        ('medium', 'Medium'),
                        ('high', 'High'),
                        ('urgent', 'Urgent')
                    ],
                    default='medium',
                    max_length=10
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('assigned_to_support', models.ForeignKey(
                    blank=True,
                    help_text='Support team member assigned to this ticket',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='support_assigned_tickets',
                    to=settings.AUTH_USER_MODEL
                )),
                ('created_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='created_tickets',
                    to=settings.AUTH_USER_MODEL
                )),
                ('forwarded_to_user', models.ForeignKey(
                    blank=True,
                    help_text='Specific user from the role who is handling the ticket',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='forwarded_tickets',
                    to=settings.AUTH_USER_MODEL
                )),
                ('resolved_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_tickets',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='history',
                    to='models_app.supportticket'
                )),
                ('user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='ticket_actions',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name_plural': 'Ticket histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(
                    default=False,
                    help_text='Internal comments visible only to staff'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='models_app.supportticket'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ticket_comments',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='models_app__status_3e5a19_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_by', 'status'], name='models_app__created_82f6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['forwarded_to_role', 'status'], name='models_app__forward_9b4a21_idx'),
        ),
    ]
