# Generated by Django 4.2.15 on 2025-11-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_supportticket_ticketcomment_tickethistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='models_app__receive_fa9ca7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='models_app__created_02bb31_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='models_app__sender__700a72_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='models_app__region_ba8f05_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='models_app__crop_ty_368421_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='models_app__status_b58dff_idx',
            old_name='models_app__status_3e5a19_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='models_app__created_667958_idx',
            old_name='models_app__created_82f6cd_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='models_app__forward_7226fd_idx',
            old_name='models_app__forward_9b4a21_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='region',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='template',
        ),
    ]
