name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: oelp
          POSTGRES_USER: oelp
          POSTGRES_PASSWORD: oelp
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U oelp"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SECRET_KEY: test-secret
      DJANGO_DEBUG: 'false'
      DB_ENGINE: django.contrib.gis.db.backends.postgis
      DB_NAME: oelp
      DB_USER: oelp
      DB_PASSWORD: oelp
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      CORS_ALLOW_ALL: 'true'
      DJANGO_ALLOWED_HOSTS: '127.0.0.1,localhost'
      DJANGO_TIME_ZONE: 'UTC'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libgeos-dev libproj-dev libpq-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks and migrations
        run: |
          python oelp_backend/manage.py check
          python oelp_backend/manage.py migrate --noinput
